# Site settings
title: "Careers at Major League Hacking (MLH)"
description: "A collection of jobs for hackers and other superheroes. Start a career at Major League Hacking."
baseurl: ""
url: "http://careers.mlh.io"

# Build settings
markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
